name: Smoke tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  calendly:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/shared-steps
    - name: Run Calendly
      env:
        LILA_API_KEY: ${{ secrets.LILA_API_KEY  }}
      run: |
        lila run tests/calendly.yaml --headless
