name: Lila daily run

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  no-auth:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install lila cli
      run: |
        pip install lilacli
        playwright install chrome chromium
    - name: Run no-auth tests
      env:
        LILA_API_KEY: ${{ secrets.LILA_API_KEY  }}
      run: |
        lila run tests --tags no-auth
