name: Lila

on:
  workflow_dispatch:
#   schedule:
#     - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  no-auth:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install lila cli
      run: |
        pip install lilacli
        playwright install chrome chromium
    - name: Run no-auth tests
      env:
        LILA_API_KEY: ${{ secrets.LILA_API_KEY  }}
      run: |
        lila run tests --tags no-auth
  spotify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install lila cli
      run: |
        pip install lilacli
        playwright install chrome chromium
    - name: Run login test
      env:
        LILA_API_KEY: ${{ secrets.LILA_API_KEY  }}
        SPOTIFY_USERNAME: i.itz
        SPOTIFY_PASSWORD: ${{ secrets.SPOTIFY_PASSWORD }}
      run: |
        lila run tests/spotify-login.yaml --output-dir tests-output
    - name: Run dashboard tests
      env:
        LILA_API_KEY: ${{ secrets.LILA_API_KEY  }}
      run: |
        lila run tests/spotify-dashboard.yaml --browser-state tests-output/tests/spotify-login.json
  helicone:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install lila cli
      run: |
        pip install lilacli
        playwright install chrome chromium
    - name: Run login test
      env:
        LILA_API_KEY: ${{ secrets.LILA_API_KEY  }}
        HELICONE_USERNAME: surfing.devs@gmail.com
        HELICONE_PASSWORD: ${{ secrets.HELICONE_PASSWORD }}
      run: |
        lila run tests/helicone-login.yaml --output-dir tests-output
    - name: Run dashboard tests
      env:
        LILA_API_KEY: ${{ secrets.LILA_API_KEY  }}
      run: |
        lila run tests/helicone-dashboard.yaml --browser-state tests-output/tests/helicone-login.json
